#!/bin/bash

#PBS -l nodes=1:ppn=1 
#PBS -l walltime=00:10:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_report
mkdir -p out_figs

singularity exec docker://brainlife/mne:1.2.1 python3 main.py


